# Generated by Django 5.1.1 on 2025-02-03 18:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(editable=False, help_text='A unique identifier for the Book starting with B', max_length=255, primary_key=True, serialize=False, verbose_name='Book ID')),
                ('name', models.CharField(db_index=True, help_text='Title of the book', max_length=255)),
                ('author', models.CharField(db_index=True, help_text='Author of the book', max_length=255)),
                ('edition', models.CharField(blank=True, help_text='Edition of the book', max_length=50, null=True)),
                ('publisher', models.CharField(blank=True, help_text='Publisher of the book', max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, db_index=True, help_text='ISBN number', max_length=13, null=True, unique=True)),
                ('genre', models.CharField(blank=True, help_text='Genre of the book', max_length=100, null=True)),
                ('language', models.CharField(blank=True, help_text='Language of the book', max_length=50, null=True)),
                ('num_pages', models.PositiveIntegerField(blank=True, help_text='Number of pages', null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image of the book', null=True, upload_to='book_covers/')),
                ('file', models.FileField(blank=True, help_text='Upload the digital version of the book (PDF, ePub, etc.)', null=True, upload_to='book_files/')),
                ('access_type', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', help_text='Defines whether the book is public or private', max_length=7)),
                ('access_code', models.CharField(blank=True, help_text='Access code for private books.', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the book was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the book details were last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.CharField(editable=False, help_text='Unique identifier for the class, combines "C", username of the creator, and an incrementing number', max_length=255, primary_key=True, serialize=False, verbose_name='Class ID')),
                ('name', models.CharField(help_text='Subject + Class Example(Java MCA-1)', max_length=255, verbose_name='Class Name')),
                ('description', models.TextField(blank=True, help_text='A brief description of the class including objectives and syllabus', null=True, verbose_name='Class Description')),
                ('current_topic', models.CharField(blank=True, help_text='Current topic of the class', max_length=255, null=True, verbose_name='Current Topic')),
                ('last_topic', models.CharField(blank=True, help_text='last topic of the class', max_length=255, null=True, verbose_name='last Topic')),
                ('next_topic', models.CharField(blank=True, help_text='next topic of the class', max_length=255, null=True, verbose_name='next Topic')),
                ('next_class_date', models.DateTimeField(blank=True, help_text='Date and Time when the class is gonna be ', null=True, verbose_name='Next Class Date and Time')),
                ('textbooks', models.JSONField(blank=True, default=list, help_text='Store multiple textbook names in JSON format as a list. ["Alice", "Bob", "Charlie", "David"]', null=True, verbose_name='textbooks')),
                ('max_students', models.PositiveIntegerField(default=30, help_text='Maximum number of students allowed in this class', verbose_name='Maximum Students')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the class is currently active', verbose_name='Is Active')),
                ('schedule', models.JSONField(blank=True, default=list, help_text='Class schedule in JSON format. Example: ["9 AM","12 PM","2 PM"]', verbose_name='Schedule')),
                ('syllabus_file', models.FileField(blank=True, help_text='Upload the syllabus as a file (PDF or other formats).', null=True, upload_to='syllabus_files/', verbose_name='Syllabus (File)')),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='Class access type: Public or Private', max_length=7, verbose_name='Access Type')),
                ('access_code', models.CharField(blank=True, help_text='Access code required for private class enrollment', max_length=128, null=True, verbose_name='Access Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('book_used_class', models.ManyToManyField(help_text='Textbook of the class, specify if it is in the library', related_name='Class', to='Users.book', verbose_name='book_used_class')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.CharField(editable=False, help_text='Unique identifier for the quiz, combines "K", user_id, and an incrementing number', max_length=50, primary_key=True, serialize=False, verbose_name='Quiz ID')),
                ('name', models.CharField(help_text='Subject : Topic Example : Java: AWT Classes', max_length=255, verbose_name='Quiz Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('access_code', models.CharField(blank=True, help_text='Access code required for private quiz', max_length=128, null=True, verbose_name='Access Code')),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10, verbose_name='Access Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('time_limit', models.DurationField(blank=True, help_text='Time limit for the quiz in hours, minutes, and seconds', null=True, verbose_name='Time Limit')),
                ('valid_till', models.DateTimeField(blank=True, help_text='Date and time until which the quiz will be available', null=True, verbose_name='Valid Till')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('assigned_classes', models.ManyToManyField(blank=True, help_text='Classes to which this quiz is assigned', related_name='quizzes', to='Users.class', verbose_name='Assigned Classes')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.CharField(editable=False, help_text='Unique identifier for the question, combines "Q", quiz_id, and an incrementing number', max_length=100, primary_key=True, serialize=False, verbose_name='Question ID')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice Question'), ('text', 'Text Response'), ('true_false', 'True/False Question')], help_text='The type of question: MCQ, Text-(Long or Short), or True/False', max_length=10, verbose_name='Question Type')),
                ('question_text', models.TextField(help_text='The text of the question', verbose_name='Question Text')),
                ('correct_option', models.TextField(blank=True, help_text='The correct answer (applicable for MCQ and True/False questions) Example : "Paris" or "True"', null=True, verbose_name='Correct Option')),
                ('options', models.JSONField(blank=True, help_text='JSON object containing options for MCQ and True/False Example ["Paris", "London", "Berlin", "Rome"] ', null=True, verbose_name='Options')),
                ('marks', models.IntegerField(default=1, help_text='Marks allocated for this question', verbose_name='Marks')),
                ('negative_marks', models.FloatField(default=0.0, help_text='Marks deducted for an incorrect answer', verbose_name='Negative Marks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('quiz', models.ForeignKey(help_text='The quiz to which this question belongs', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Users.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['quiz', 'question_id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('title', models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'User',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='Users to whom this quiz is assigned', related_name='assigned_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Quiz Assigned To User'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_saved_by_users',
            field=models.ManyToManyField(blank=True, help_text='Users who saved this quiz', related_name='quiz_saved_by_users', to=settings.AUTH_USER_MODEL, verbose_name='Saved by users'),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('notes_id', models.CharField(editable=False, help_text='Unique identifier for the notes, combines "N", username of creator and creation timestamp', max_length=100, primary_key=True, serialize=False, verbose_name='Notes ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('access_code', models.CharField(blank=True, help_text='Access code required for private notes', max_length=128, null=True, verbose_name='Access Code')),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='Type of access: Public or Private', max_length=7, verbose_name='Access Type')),
                ('topic', models.CharField(blank=True, help_text='Parent/related topic of the notes', max_length=100, null=True)),
                ('notes_file', models.FileField(blank=True, help_text='The actual notes document file (PDF, Word, etc.)', null=True, upload_to='notes_files/', verbose_name='Notes File')),
                ('pretext', models.TextField(blank=True, help_text='A brief pretext on what is covered and what is not', null=True, verbose_name='pretext')),
                ('textbook', models.TextField(blank=True, help_text='Textbook from which notes are created', null=True, verbose_name='Textbook referred')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('book_used_notes', models.ForeignKey(blank=True, help_text='Book used to create the notes, specify if it is in the library', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='Users.book', verbose_name='book_used_notes')),
                ('class_belongs_to', models.ManyToManyField(blank=True, help_text='Classes to which these notes belong', related_name='notes', to='Users.class', verbose_name='Classes to which these notes belong')),
                ('created_by', models.ForeignKey(help_text='The user who created this note (likely a teacher or admin)', on_delete=django.db.models.deletion.CASCADE, related_name='created_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('notes_saved_by_users', models.ManyToManyField(blank=True, help_text='Users who saved this notes', related_name='notes_saved_by_users', to=settings.AUTH_USER_MODEL, verbose_name='Saved by Users')),
            ],
            options={
                'verbose_name': 'Notes',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='created_by',
            field=models.ForeignKey(help_text='Teacher who created the class', limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_classes', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='class',
            name='next_class_teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher who will take the next scheduled class', limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_class_teacher', to=settings.AUTH_USER_MODEL, verbose_name='next_class_teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Students enrolled in this class', limit_choices_to={'user_type': 'student'}, related_name='enrolled_students', to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(help_text='Teachers assigned to this class', limit_choices_to={'user_type': 'teacher'}, related_name='class_teachers', to=settings.AUTH_USER_MODEL, verbose_name='Teachers'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_saved_by_users',
            field=models.ManyToManyField(blank=True, help_text='Users who saved this book', related_name='book_saved_by_users', to=settings.AUTH_USER_MODEL, verbose_name='Saved by users'),
        ),
        migrations.AddField(
            model_name='book',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('attempt_id', models.CharField(editable=False, help_text='Unique identifier for the attempt, combining quiz_id, username, and timestamp', max_length=255, primary_key=True, serialize=False, verbose_name='Attempt ID')),
                ('marks_scored', models.FloatField(default=0.0, help_text='Marks scored by the user in this attempt', verbose_name='Marks Scored')),
                ('total_marks', models.FloatField(blank=True, help_text='The total possible marks for the quiz', null=True, verbose_name='Total Marks')),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', help_text='The status of the result: Passed, Failed, or Pending', max_length=10, verbose_name='Status')),
                ('attempt_time', models.DateTimeField(help_text='Timestamp when the attempt started', verbose_name='Attempt Time')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the attempt was completed', null=True, verbose_name='Completed At')),
                ('duration', models.FloatField(blank=True, help_text='Time taken to complete the quiz', null=True, verbose_name='Duration')),
                ('remaining_time', models.FloatField(blank=True, help_text='Remaining time left in the quiz', null=True, verbose_name='Remaining Time')),
                ('question_start_timestamp', models.DateTimeField(blank=True, help_text='When the start question ended', null=True, verbose_name='start question timestmap')),
                ('completion_reason', models.CharField(blank=True, choices=[('timeout', 'Time Ran Out'), ('all_answered', 'All Questions Answered')], help_text='Reason why the quiz was completed', max_length=15, null=True, verbose_name='Completion Reason')),
                ('unvisited_questions', models.IntegerField(default=0, help_text='Number of unanswered questions when the attempt ended', verbose_name='Unvisited Questions')),
                ('visited_questions', models.IntegerField(default=0, help_text='Number of answered questions when the attempt ended', verbose_name='visited Questions')),
                ('feedback', models.TextField(blank=True, help_text='Feedback or comments for the student on the result', null=True, verbose_name='Feedback')),
                ('quiz', models.ForeignKey(help_text='Quiz being attempted', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='Users.quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(help_text='User attempting the quiz', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Attempt',
                'verbose_name_plural': 'Attempts',
                'ordering': ['-attempt_time'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.CharField(editable=False, help_text='A unique identifier for the announcement starting with A', max_length=255, primary_key=True, serialize=False, verbose_name='Announcement ID')),
                ('title', models.CharField(blank=True, help_text='Title of the announcement', max_length=255, null=True, verbose_name='Announcement Title')),
                ('content', models.TextField(help_text='The detailed content of the announcement', verbose_name='Announcement Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('expire_at', models.DateTimeField(blank=True, help_text='Date and time when the announcement will expire', null=True, verbose_name='Expires At')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('student', 'Student'), ('teacher', 'Teacher')], default='public', help_text='Who can view this announcement?', max_length=12, verbose_name='Visibility')),
                ('priority', models.CharField(choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', help_text='Priority level of the announcement', max_length=20, verbose_name='Priority')),
                ('attachment', models.FileField(blank=True, help_text='Optional file attachment for the announcement', null=True, upload_to='announcement_attachments/', verbose_name='Attachment')),
                ('is_pinned', models.BooleanField(db_index=True, default=False, help_text='If the announcement should be pinned at the top of the list', verbose_name='Pinned')),
                ('Class', models.ForeignKey(blank=True, help_text='The class for which this announcement is made', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='Users.class', verbose_name='Class')),
                ('created_by', models.ForeignKey(help_text='Teacher who created the announcement', on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('selected_option', models.CharField(blank=True, max_length=255, null=True)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_scored', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='Users.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Users.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Users.quiz')),
                ('answered_by', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['answered_at'],
                'unique_together': {('quiz', 'question', 'answered_by')},
            },
        ),
    ]
