# Generated by Django 5.1.1 on 2025-02-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='completion_reason',
            field=models.CharField(blank=True, choices=[('timeout', 'Time Ran Out'), ('all_visited', 'All Questions Visited')], help_text='Reason why the quiz was completed', max_length=15, null=True, verbose_name='Completion Reason'),
        ),
    ]
