# Generated by Django 5.1.1 on 2025-02-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_attempt_completion_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='current_question_index',
            field=models.IntegerField(default=0, help_text='The questions index on which the user is on ', verbose_name='current question index'),
        ),
    ]
