# Generated by Django 5.1.1 on 2025-02-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_attempt_current_question_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='question_order',
            field=models.TextField(default='[]'),
        ),
    ]
