# Generated by Django 5.1.1 on 2025-02-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_attempt_question_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='completion_reason',
            field=models.CharField(blank=True, choices=[('timeout', 'Time Ran Out'), ('manual_submit', 'User submitted manually')], help_text='Reason why the quiz was completed', max_length=15, null=True, verbose_name='Completion Reason'),
        ),
    ]
