# Generated by Django 5.1.1 on 2025-02-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_attempt_completion_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='unvisited_questions',
        ),
    ]
