# Generated by Django 5.1.1 on 2025-02-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_remove_attempt_unvisited_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='visited_questions',
        ),
    ]
