# Generated by Django 5.1.1 on 2025-02-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_remove_attempt_visited_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='wrong_notAttempted',
            field=models.TextField(blank=True, default='[]', help_text='Stores the questions that were answered incorrectly or not attempted', null=True, verbose_name='Wrong or Not Attempted Questions'),
        ),
    ]
