# Generated by Django 5.1.1 on 2025-02-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_attempt_wrong_notattempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, help_text='Optional image related to the question', null=True, upload_to='question_images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='question',
            name='remarks',
            field=models.TextField(blank=True, help_text='Explanation or remarks on why the option is correct', null=True, verbose_name='Remarks'),
        ),
    ]
