# Generated by Django 5.1.1 on 2025-02-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_question_question_image_question_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='success_rate',
            field=models.JSONField(default=dict, help_text='Tracks attempts and correct answers, e.g., {"attempts": 0, "correct": 0}', verbose_name='Success Rate'),
        ),
    ]
