# Generated by Django 5.1.1 on 2025-02-13 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_question_success_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Time when the quiz becomes available for responses', null=True, verbose_name='Start Time'),
        ),
    ]
