# Generated by Django 5.1.1 on 2025-02-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_quiz_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='valid_till',
        ),
        migrations.AddField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Time after which the quiz will stop accepting responses', null=True, verbose_name='End Time'),
        ),
    ]
