# Generated by Django 5.1.1 on 2025-02-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_remove_quiz_valid_till_quiz_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='average_duration',
            field=models.DurationField(blank=True, help_text='Average time taken by users to complete this quiz', null=True, verbose_name='Average Duration'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='average_marks',
            field=models.FloatField(default=0.0, help_text='Average marks scored by users in this quiz', verbose_name='Average Marks'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Total number of attempts made for this quiz', verbose_name='Total Attempts'),
        ),
    ]
