# Generated by Django 5.1.1 on 2025-02-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_quiz_average_duration_quiz_average_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='average_duration',
            field=models.FloatField(blank=True, help_text='Average time taken by users to complete this quiz', null=True, verbose_name='Average Duration'),
        ),
    ]
