# Generated by Django 5.1.1 on 2025-02-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_alter_quiz_average_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='recent_marks_duration_1000',
            field=models.JSONField(default=list, help_text='List of the most recent 1000 marks and durations for calculating averages', verbose_name='Recent Marks and Durations (1000)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='standard_deviation',
            field=models.FloatField(default=0.0, help_text='Standard deviation of marks scored in this quiz', verbose_name='Standard Deviation'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='current_question_index',
            field=models.IntegerField(default=0, help_text='The questions index on which the user is on, starts with 0', verbose_name='current question index'),
        ),
    ]
