# Generated by Django 5.1.1 on 2025-02-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_quiz_recent_marks_duration_1000_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='standard_deviation',
        ),
        migrations.AddField(
            model_name='quiz',
            name='standard_deviation_duration',
            field=models.FloatField(default=0.0, help_text='Standard deviation of duration in this quiz', verbose_name='Standard Deviation Duration'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='standard_deviation_marks',
            field=models.FloatField(default=0.0, help_text='Standard deviation of marks scored in this quiz', verbose_name='Standard Deviation Marks'),
        ),
    ]
