# Generated by Django 5.1.1 on 2025-02-26 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_remove_quiz_standard_deviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='schedule',
            field=models.JSONField(blank=True, default=list, help_text='Class schedule in JSON format. Example: ["9 AM","None","12 PM","2 PM","None","10 AM"]', verbose_name='Schedule'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, verbose_name='Assignment ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Users.class', verbose_name='Class')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('assignment_submission_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, verbose_name='Assignment Submission ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignment_submissions/', verbose_name='File Submission')),
                ('text_response', models.TextField(blank=True, null=True, verbose_name='Text Response')),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Marks')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Users.assignment', verbose_name='Assignment')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By')),
            ],
            options={
                'ordering': ['submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'submitted_by'), name='unique_submission_per_user')],
            },
        ),
    ]
