# Generated by Django 5.1.1 on 2025-02-26 09:12

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_alter_class_schedule_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_files/',  verbose_name='File Attachment'),
        ),
    ]
