# Generated by Django 5.1.1 on 2025-03-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notes_link',
            field=models.URLField(blank=True, help_text='Provide a link if the notes are available online', null=True, verbose_name='Notes URL'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, help_text='Edition of the book in words', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='schedule',
            field=models.JSONField(blank=True, default=list, help_text='Class schedule in JSON format. Example: ["9 AM","None","12 PM","2 PM","None","10 AM","None"]', verbose_name='Schedule'),
        ),
    ]
