# Generated by Django 5.1.1 on 2025-03-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_notes_notes_link_alter_book_edition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='percentile_marks',
            field=models.FloatField(default=0.0, help_text='Percentile rank of the user’s score in the quiz', verbose_name='Percentile Marks'),
        ),
    ]
