# Generated by Django 5.1.1 on 2025-03-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_attempt_percentile_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='percentile_duration',
            field=models.FloatField(blank=True, help_text='Percentile rank of the user’s quiz completion time', null=True, verbose_name='Percentile Duration'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='percentile_marks',
            field=models.FloatField(blank=True, help_text='Percentile rank of the user’s score in the quiz', null=True, verbose_name='Percentile Marks'),
        ),
    ]
