# Generated by Django 5.1.1 on 2025-03-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_attempt_percentile_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_marks',
            field=models.FloatField(blank=True, help_text='The total possible marks for the quiz', null=True, verbose_name='Total Marks'),
        ),
    ]
