# Generated by Django 5.1.1 on 2025-03-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0022_remove_attempt_total_marks_quiz_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='rating',
            field=models.FloatField(blank=True, help_text='Rating given by the user for this attempt (out of 5 stars)', null=True, verbose_name='Attempt Rating'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='rating',
            field=models.FloatField(default=0.0, help_text='Average rating of this quiz out of 5 stars', verbose_name='Quiz Rating'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0, help_text='Total number of ratings given for this quiz', verbose_name='Total Ratings'),
        ),
    ]
