# Generated by Django 5.1.1 on 2025-03-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0023_attempt_rating_quiz_rating_quiz_total_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='question_order',
            field=models.JSONField(default=list),
        ),
    ]
