# Generated by Django 5.1.1 on 2025-03-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0024_alter_attempt_question_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='Rating given by the user for this attempt (out of 5 stars)', null=True, verbose_name='Attempt Rating'),
        ),
    ]
