# Generated by Django 5.1.1 on 2025-03-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0026_alter_quiz_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='rating',
            field=models.FloatField(blank=True, help_text='Average rating of this quiz out of 5 stars', null=True, verbose_name='Quiz Rating'),
        ),
    ]
