# Generated by Django 5.1.1 on 2025-03-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0028_alter_quiz_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('objective', 'MCQ / True-False (Auto Evaluation)'), ('objective_and_subjective', 'MCQ / True-False / Text (Mixed)')], default='objective', help_text='Select the type of questions for this quiz', max_length=25, verbose_name='Quiz Type'),
        ),
    ]
