# Generated by Django 5.1.1 on 2025-03-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0029_quiz_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='unchecked_manual_question',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='manual_questions_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
