# Generated by Django 5.1.1 on 2025-03-10 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0030_attempt_unchecked_manual_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='unchecked_manual_question',
        ),
    ]
