# Generated by Django 5.1.1 on 2025-03-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0031_remove_attempt_unchecked_manual_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='manual_questions_count',
        ),
        migrations.AddField(
            model_name='quiz',
            name='text_question_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of question IDs that are of type text (subjective questions).', verbose_name='Text-Based Questions'),
        ),
        migrations.AlterField(
            model_name='question',
            name='success_rate',
            field=models.JSONField(blank=True, default=dict, help_text='Tracks attempts and correct answers, e.g., {"attempts": 0, "correct": 0}', verbose_name='Success Rate'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='recent_marks_duration_1000',
            field=models.JSONField(blank=True, default=list, help_text='List of the most recent 1000 marks and durations for calculating averages', verbose_name='Recent Marks and Durations (1000)'),
        ),
    ]
