# Generated by Django 5.1.1 on 2025-03-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0032_remove_quiz_manual_questions_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='is_reviewed',
        ),
    ]
