# Generated by Django 5.1.1 on 2025-03-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0033_remove_answer_is_correct_remove_answer_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
