# Generated by Django 5.1.1 on 2025-03-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0034_answer_is_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='average_duration',
            field=models.FloatField(default=0.0, help_text='Average time taken by users to complete this quiz', verbose_name='Average Duration'),
        ),
    ]
