# Generated by Django 5.1.1 on 2025-03-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0035_alter_quiz_average_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='text_question_ids',
        ),
    ]
