# Generated by Django 5.1.1 on 2025-03-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0036_remove_quiz_text_question_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='question_status',
            field=models.JSONField(default=dict),
        ),
    ]
