# Generated by Django 5.1.1 on 2025-03-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0037_attempt_question_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='percentile_duration',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='percentile_marks',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='average_duration',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='average_marks',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='recent_marks_duration_1000',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='standard_deviation_duration',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='standard_deviation_marks',
        ),
        migrations.AddField(
            model_name='attempt',
            name='percentile_weighted_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='weighted_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='history_limit',
            field=models.PositiveIntegerField(default=1000, help_text='Number of recent weighted scores to keep for calculating averages', verbose_name='History Limit'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='weight_duration',
            field=models.FloatField(default=0.5, help_text='Weight given to duration in weighted score calculation', verbose_name='Weight for Duration'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='weight_marks',
            field=models.FloatField(default=0.5, help_text='Weight given to marks in weighted score calculation', verbose_name='Weight for Marks'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='weighted_score_avg',
            field=models.FloatField(default=0.0, help_text='Average of recent weighted scores', verbose_name='Weighted Score Average'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='weighted_score_std_dev',
            field=models.FloatField(default=0.0, help_text='Standard deviation of recent weighted scores', verbose_name='Weighted Score Standard Deviation'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='weighted_scores_history',
            field=models.JSONField(blank=True, default=list, help_text='List of recent weighted scores used for calculating averages', verbose_name='Weighted Scores History'),
        ),
    ]
