# Generated by Django 5.1.1 on 2025-03-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0038_remove_attempt_percentile_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='weighted_scores_history',
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_marks',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Marks'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='min_duration',
            field=models.FloatField(default=0.0, verbose_name='Minimum Duration'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='min_marks',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Marks'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='score_history',
            field=models.JSONField(blank=True, default=list, help_text='List of recent weighted scores and ac used for calculating averages', verbose_name=' Scores History'),
        ),
    ]
