# Generated by Django 5.1.1 on 2025-03-30 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0039_remove_quiz_total_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expire_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the announcement will expire', verbose_name='Expires At'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='timezone.now', help_text='Title of the announcement', max_length=128, verbose_name='Announcement Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('student', 'Student'), ('teacher', 'Teacher')], default='student', help_text='Who can view this announcement?', max_length=12, verbose_name='Visibility'),
        ),
    ]
