# Generated by Django 5.1.1 on 2025-04-02 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0040_alter_announcement_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='Class',
            field=models.ForeignKey(default='MCA-2A', help_text='The class for which this announcement is made', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='Users.class', verbose_name='Class'),
            preserve_default=False,
        ),
    ]
