# Generated by Django 5.1.1 on 2025-04-05 18:58

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0042_alter_user_date_of_birth_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='access_code',
            field=models.CharField(blank=True, default='', help_text='Access code required for private quiz', max_length=128, verbose_name='Access Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='score_history',
            field=models.JSONField(default=list, help_text='List of recent weighted scores and ac used for calculating averages', verbose_name=' Scores History'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time when the quiz becomes available for responses', verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), help_text='Time limit for the quiz in hours, minutes, and seconds', verbose_name='Time Limit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.')], default='Mr.', max_length=10),
        ),
    ]
