# Generated by Django 5.1.1 on 2025-04-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0043_alter_quiz_access_code_alter_quiz_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.TextField(blank=True, default='', help_text='The correct answer (applicable for MCQ and True/False questions) Example : Paris or True', verbose_name='Correct Option'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(default=list, help_text='JSON object containing options for MCQ and True/False Example ["Paris", "London", "Berlin", "Rome"] ', verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice Question'), ('text', 'Text Response'), ('true_false', 'True/False Question')], default='mcq', help_text='The type of question: MCQ, Text-(Long or Short), or True/False', max_length=10, verbose_name='Question Type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='remarks',
            field=models.TextField(blank=True, default='', help_text='Explanation or remarks on why the option is correct', verbose_name='Remarks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='success_rate',
            field=models.JSONField(default=dict, help_text='Tracks attempts and correct answers, e.g., {"attempts": 0, "correct": 0}', verbose_name='Success Rate'),
        ),
    ]
