# Generated by Django 5.1.1 on 2025-04-05 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0045_alter_answer_attempt_alter_answer_selected_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='Users.attempt'),
        ),
    ]
