# Generated by Django 5.1.1 on 2025-04-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0046_alter_answer_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='completion_reason',
            field=models.CharField(blank=True, choices=[('timeout', 'Time Ran Out'), ('manual_submit', 'User submitted manually')], default='timeout', help_text='Reason why the quiz was completed', max_length=15, verbose_name='Completion Reason'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attempt',
            name='feedback',
            field=models.TextField(blank=True, default='', help_text='Feedback or comments for the student on the result', verbose_name='Feedback'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attempt',
            name='question_start_timestamp',
            field=models.DateTimeField(default='2025-03-30 19:15:42.123456+00:00', help_text='When the start question ended', verbose_name='start question timestmap'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attempt',
            name='rating',
            field=models.PositiveIntegerField(default=0, help_text='Rating given by the user for this attempt (out of 5 stars)', verbose_name='Attempt Rating'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='remaining_time',
            field=models.FloatField(default=0, help_text='Remaining time left in the quiz', verbose_name='Remaining Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attempt',
            name='wrong_notAttempted',
            field=models.JSONField(default=list),
        ),
    ]
