# Generated by Django 5.1.1 on 2025-04-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0047_alter_attempt_completion_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='current_topic',
            field=models.CharField(blank=True, default='', help_text='Current topic of the class', max_length=255, verbose_name='Current Topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, default='', help_text='A brief description of the class including objectives and syllabus', verbose_name='Class Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='last_topic',
            field=models.CharField(blank=True, default='', help_text='last topic of the class', max_length=255, verbose_name='last Topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='next_topic',
            field=models.CharField(blank=True, default='', help_text='next topic of the class', max_length=255, verbose_name='next Topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='access_code',
            field=models.CharField(blank=True, help_text='Access code required for private quiz', max_length=128, null=True, verbose_name='Access Code'),
        ),
    ]
