# Generated by Django 5.1.1 on 2025-04-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0048_alter_class_current_topic_alter_class_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='schedule',
            field=models.JSONField(default=list, help_text='Class schedule in JSON format. Example: ["9 AM","None","12 PM","2 PM","None","10 AM","None"]', verbose_name='Schedule'),
        ),
    ]
