# Generated by Django 5.1.1 on 2025-04-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0050_alter_class_textbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='textbooks',
            field=models.JSONField(blank=True, default=list, help_text='Store multiple textbook names in JSON format as a list. ["Alice", "Bob", "Charlie", "David"]', null=True, verbose_name='textbooks'),
        ),
    ]
