# Generated by Django 5.1.1 on 2025-04-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0051_alter_class_textbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='schedule',
            field=models.JSONField(blank=True, default=list, help_text='Class schedule in JSON format. Example: ["9 AM","None","12 PM","2 PM","None","10 AM","None"]', verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='class_belongs_to',
            field=models.ManyToManyField(help_text='Classes to which these notes belong', related_name='notes', to='Users.class', verbose_name='Classes to which these notes belong'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='pretext',
            field=models.TextField(blank=True, default='', help_text='A brief pretext on what is covered and what is not', verbose_name='pretext'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='textbook',
            field=models.TextField(blank=True, default='', help_text='Textbook from which notes are created', verbose_name='Textbook referred'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='topic',
            field=models.CharField(default='', help_text='Parent/related topic of the notes', max_length=100),
            preserve_default=False,
        ),
    ]
