# Generated by Django 5.1.1 on 2025-04-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0052_alter_class_schedule_alter_notes_class_belongs_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True, default='', verbose_name='Feedback'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Marks'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='text_response',
            field=models.TextField(blank=True, default='', verbose_name='Text Response'),
            preserve_default=False,
        ),
    ]
