# Generated by Django 5.1.1 on 2025-04-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0053_alter_assignmentsubmission_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='', help_text='Cover image of the book', upload_to='book_covers/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(default='', help_text='Upload the digital version of the book (PDF, ePub, etc.)', upload_to='book_files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, default='', help_text='Genre of the book', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(db_index=True, default='', help_text='ISBN number', max_length=17, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default='', help_text='Language of the book', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, default='', help_text='Publisher of the book', max_length=255),
            preserve_default=False,
        ),
    ]
