# Generated by Django 5.1.1 on 2025-04-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0054_alter_book_cover_image_alter_book_edition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.PositiveIntegerField(default='', help_text='Edition of the book in words'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, help_text='Genre of the book', max_length=100, null=True),
        ),
    ]
