# Generated by Django 5.1.1 on 2025-04-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0055_alter_book_edition_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, default='', help_text='Genre of the book', max_length=100),
            preserve_default=False,
        ),
    ]
