# Generated by Django 5.1.1 on 2025-04-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0056_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.PositiveIntegerField(blank=True, help_text='Edition of the book in words'),
        ),
    ]
