# Generated by Django 5.1.1 on 2025-04-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0057_alter_book_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image of the book', null=True, upload_to='book_covers/'),
        ),
    ]
