# Generated by Django 5.1.1 on 2025-04-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0058_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='class_belongs_to',
            field=models.ManyToManyField(blank=True, help_text='Classes to which these notes belong', null=True, related_name='notes', to='Users.class', verbose_name='Classes to which these notes belong'),
        ),
    ]
