# Generated by Django 5.1.1 on 2025-04-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0059_alter_notes_class_belongs_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='feedback',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
    ]
