# Generated by Django 5.1.1 on 2025-04-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0060_remove_assignmentsubmission_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='class_belongs_to',
            field=models.ManyToManyField(blank=True, help_text='Classes to which these notes belong', related_name='notes', to='Users.class', verbose_name='Classes to which these notes belong'),
        ),
    ]
