# Generated by Django 5.1.1 on 2025-04-06 15:40

import Users.models
import django.core.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0061_alter_notes_class_belongs_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment for the announcement', null=True, upload_to='announcement_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt', 'doc']), Users.models.validate_file_size], verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt', 'doc']), Users.models.validate_file_size], verbose_name='File Attachment'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt', 'doc']), Users.models.validate_file_size], verbose_name='File Submission'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='duration',
            field=models.FloatField(blank=True, help_text='Time taken to complete the quiz', null=True, validators=[django.core.validators.MaxValueValidator(0)], verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='rating',
            field=models.PositiveIntegerField(default=0, help_text='Rating given by the user for this attempt (out of 5 stars)', validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Attempt Rating'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='remaining_time',
            field=models.FloatField(help_text='Remaining time left in the quiz', validators=[django.core.validators.MaxValueValidator(0)], verbose_name='Remaining Time'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image of the book', null=True, upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg']), functools.partial(Users.models.validate_file_size, *(), **{'max_size_mb': 25})]),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notes_file',
            field=models.FileField(blank=True, help_text='The actual notes document file (PDF, Word, etc.)', null=True, upload_to='notes_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt', 'doc']), Users.models.validate_file_size], verbose_name='Notes File'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, help_text='Optional image related to the question', null=True, upload_to='question_images/', validators=[Users.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg'])], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='rating',
            field=models.PositiveIntegerField(default=0, help_text='Average rating of this quiz out of 5 stars', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quiz Rating'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='weight_duration',
            field=models.FloatField(default=0.5, help_text='Weight given to duration in weighted score calculation', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Weight for Duration'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='weight_marks',
            field=models.FloatField(default=0.5, help_text='Weight given to marks in weighted score calculation', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Weight for Marks'),
        ),
    ]
