# Generated by Django 5.1.1 on 2025-04-06 15:41

import Users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0062_alter_announcement_attachment_alter_assignment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.PositiveIntegerField(blank=True, help_text='Edition of the book in words', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(help_text='Upload the digital version of the book (PDF, ePub, etc.)', upload_to='book_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt', 'doc', 'epub']), Users.models.validate_file_size]),
        ),
    ]
