# Generated by Django 5.1.1 on 2025-04-10 07:32

import Users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0063_alter_book_edition_alter_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='duration',
            field=models.FloatField(blank=True, help_text='Time taken to complete the quiz', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='rating',
            field=models.PositiveIntegerField(default=0, help_text='Rating given by the user for this attempt (out of 5 stars)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Attempt Rating'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='remaining_time',
            field=models.FloatField(help_text='Remaining time left in the quiz', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Remaining Time'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='wrong_notAttempted',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='class',
            name='book_used_class',
            field=models.ManyToManyField(blank=True, help_text='Textbook of the class, specify if it is in the library', related_name='Class', to='Users.book', verbose_name='book_used_class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='syllabus_file',
            field=models.FileField(blank=True, help_text='Upload the syllabus as a file (PDF or other formats).', null=True, upload_to='syllabus_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt', 'doc']), Users.models.validate_file_size], verbose_name='Syllabus (File)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='score_history',
            field=models.JSONField(blank=True, default=list, help_text='List of recent weighted scores and ac used for calculating averages', verbose_name=' Scores History'),
        ),
    ]
