# Generated by Django 5.1.1 on 2025-04-10 10:27

import Users.models
import django.core.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0064_alter_attempt_duration_alter_attempt_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='access_code',
            field=models.CharField(blank=True, default='', help_text='Access code for private books.', max_length=7, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image of the book', null=True, upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg']), Users.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(help_text='Upload the digital version of the book (PDF, ePub, etc.)', upload_to='book_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt', 'doc', 'epub']), functools.partial(Users.models.validate_file_size, *(), **{'max_size_mb': 25})]),
        ),
        migrations.AlterField(
            model_name='class',
            name='access_code',
            field=models.CharField(blank=True, default='', help_text='Access code required for private class enrollment', max_length=7, unique=True, verbose_name='Access Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='access_code',
            field=models.CharField(blank=True, default='', help_text='Access code required for private notes', max_length=7, unique=True, verbose_name='Access Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='access_code',
            field=models.CharField(blank=True, default='', help_text='Access code required for private quiz', max_length=7, unique=True, verbose_name='Access Code'),
            preserve_default=False,
        ),
    ]
