# Generated by Django 5.1.1 on 2025-04-10 10:48

import Users.models
import django.core.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0065_alter_book_access_code_alter_book_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image of the book', null=True, upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg']), Users.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(help_text='Upload the digital version of the book (PDF, ePub, etc.)', upload_to='book_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt', 'doc', 'epub']), functools.partial(Users.models.validate_file_size, *(), **{'max_size_mb': 100})]),
        ),
    ]
