# Generated by Django 5.1.1 on 2025-04-11 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0067_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
