# Generated by Django 5.1.1 on 2025-04-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0068_alter_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
