# Generated by Django 5.1.1 on 2025-04-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0070_relationship_user_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='from_person',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='to_person',
            new_name='to_user',
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('from_user', 'to_user')},
        ),
    ]
