# Generated by Django 5.1.1 on 2025-04-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0071_rename_from_person_relationship_from_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('friend', 'Friend')], max_length=20),
        ),
    ]
