# Generated by Django 5.1.1 on 2025-04-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0073_alter_relationship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('friend', 'Friend')], default='friend', max_length=20),
        ),
    ]
