# Generated by Django 5.1.1 on 2025-04-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0075_friends_alter_user_friends_delete_relationship'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friends',
            new_name='Friend',
        ),
    ]
