# Generated by Django 5.1.1 on 2025-04-11 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0076_rename_friends_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(through='Users.Friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
