# Generated by Django 5.1.1 on 2025-04-18 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0077_alter_user_friends'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set(),
        ),
    ]
