# Generated by Django 5.1.1 on 2025-04-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0078_alter_friend_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='access_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='PUBLIC', help_text='Defines whether the book is public or private', max_length=7),
        ),
    ]
