# Generated by Django 5.1.1 on 2025-04-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0079_alter_book_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='Assets/Quiz_logo.png', help_text='Upload a profile picture', upload_to='profile_photos/'),
        ),
    ]
