# Generated by Django 5.1.1 on 2025-04-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0080_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='Gurukul/static/Assets/Profile.png', help_text='Upload a profile picture', upload_to=''),
        ),
    ]
