# Generated by Django 5.1.1 on 2025-04-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0083_alter_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
    ]
