# Generated by Django 5.1.1 on 2025-11-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0085_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Quiz end time decided when the user start the quiz', null=True, verbose_name=' Quiz End Time'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='question_start_timestamp',
            field=models.DateTimeField(help_text='When the start question started', verbose_name='start question timestmap'),
        ),
    ]
