# Generated by Django 5.1.1 on 2025-11-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0086_attempt_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='remaining_time',
            field=models.DurationField(help_text='Remaining time left in the quiz', verbose_name='Remaining Time'),
        ),
    ]
