# Generated by Django 5.1.1 on 2025-11-28 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0087_alter_attempt_remaining_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='remaining_time',
            field=models.FloatField(help_text='Remaining time left in the quiz', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Remaining Time'),
        ),
    ]
