# Generated by Django 5.1.1 on 2025-11-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0088_alter_attempt_remaining_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='question_start_timestamp',
        ),
    ]
