# Generated by Django 5.1.1 on 2025-11-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0089_remove_attempt_question_start_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='marked_for_review',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
