# Generated by Django 5.1.1 on 2025-11-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0090_attempt_marked_for_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='marked_for_review',
            new_name='review_but_answered',
        ),
        migrations.AddField(
            model_name='attempt',
            name='review_not_answered',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
