# Generated by Django 5.1.1 on 2025-12-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0091_rename_marked_for_review_attempt_review_but_answered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='reload',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='remaining_time',
            field=models.FloatField(help_text='Remaining time left in the quiz', verbose_name='Remaining Time'),
        ),
    ]
