# Generated by Django 5.1.1 on 2025-12-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0092_attempt_reload_alter_attempt_remaining_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='completion_reason',
            field=models.CharField(blank=True, choices=[('timeout', 'Time Ran Out'), ('manual_submit', 'User submitted manually'), ('cheating', 'Cheating Detected')], help_text='Reason why the quiz was completed', max_length=15, verbose_name='Completion Reason'),
        ),
    ]
