# Generated by Django 5.1.1 on 2025-04-26 17:27

import Chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0008_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=Chat.models.generate_group_name, max_length=128, unique=True),
        ),
    ]
